backend:
  name: git-gateway
  branch: main

media_folder: "src/images"
public_folder: "/images"

collections:
  - name: "books"
    label: "Books"
    folder: "src/books"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Subtitle",
          name: "subtitle",
          widget: "string",
          required: false,
        }
      - {
          label: "Description",
          name: "description",
          widget: "text",
          required: false,
        }
      - { label: "Cover Image", name: "cover", widget: "image" }
      - { label: "Amazon Link", name: "link", widget: "string" }
